name: x3map
description: A sample command-line application with basic argument parsing.
version: 0.0.1

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  dartx: ^1.2.0
  freezed_annotation: ^3.1.0
  html: ^0.15.6
  http: ^1.5.0
  json_annotation: ^4.9.0
  windows1251: ^2.0.1

dev_dependencies:
  build_runner: ^2.7.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  lints: ^6.0.0
  test: ^1.25.6
